/** @type {import('tailwindcss').Config} */
// Tokens copied verbatim from design/stitch/home.html's `tailwind.config` script
// block (Stitch "Dunyo Luxury Tech" design system).
export default {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'on-primary': '#402d00',
        'on-tertiary-fixed': '#001a41',
        'secondary-fixed-dim': '#00e2a0',
        'on-primary-fixed': '#261900',
        'primary-fixed-dim': '#edc062',
        'on-secondary-container': '#005f41',
        'on-surface-variant': '#d1c5b2',
        tertiary: '#cddbff',
        'surface-container-low': '#1b1b1f',
        'outline-variant': '#4e4637',
        'tertiary-fixed': '#d8e2ff',
        'secondary-container': '#00e2a0',
        'surface-container-lowest': '#0d0e11',
        'tertiary-container': '#a2bfff',
        'on-secondary-fixed': '#002114',
        'error-container': '#93000a',
        'on-secondary': '#003825',
        'on-tertiary': '#002e69',
        'inverse-primary': '#7a5900',
        'inverse-surface': '#e3e2e6',
        background: '#121316',
        primary: '#ffd682',
        'primary-fixed': '#ffdea1',
        'tertiary-fixed-dim': '#adc6ff',
        'surface-container': '#1f1f23',
        surface: '#121316',
        'surface-container-highest': '#343538',
        'on-tertiary-container': '#004aa2',
        'on-error-container': '#ffdad6',
        'surface-dim': '#121316',
        'on-background': '#e3e2e6',
        'inverse-on-surface': '#303034',
        error: '#ffb4ab',
        'secondary-fixed': '#43ffbb',
        'on-error': '#690005',
        'on-secondary-fixed-variant': '#005138',
        'surface-variant': '#343538',
        'primary-container': '#e5b95c',
        'surface-container-high': '#292a2d',
        'on-surface': '#e3e2e6',
        'on-primary-container': '#654900',
        'on-primary-fixed-variant': '#5c4300',
        'surface-tint': '#edc062',
        outline: '#9a8f7e',
        'surface-bright': '#38393c',
        secondary: '#43ffbb',
        'on-tertiary-fixed-variant': '#004494',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        'space-xs': '0.25rem',
        margin: '1rem',
        'space-md': '0.75rem',
        'space-xl': '1.75rem',
        gutter: '0.75rem',
        'space-sm': '0.5rem',
        'space-lg': '1.25rem',
      },
      fontFamily: {
        'headline-md': ['Plus Jakarta Sans'],
        'price-badge': ['Space Grotesk'],
        'body-md': ['Plus Jakarta Sans'],
        'label-md': ['Space Grotesk'],
        'label-lg': ['Space Grotesk'],
        'headline-xl-mobile': ['Plus Jakarta Sans'],
        'label-sm': ['Space Grotesk'],
        'price-headline': ['Space Grotesk'],
        'body-sm': ['Plus Jakarta Sans'],
        'headline-lg-mobile': ['Plus Jakarta Sans'],
        'headline-lg': ['Plus Jakarta Sans'],
        'body-lg': ['Plus Jakarta Sans'],
        'headline-xl': ['Plus Jakarta Sans'],
      },
      fontSize: {
        'headline-md': ['18px', { lineHeight: '24px', letterSpacing: '-0.01em', fontWeight: '700' }],
        'price-badge': ['11px', { lineHeight: '14px', letterSpacing: '0.02em', fontWeight: '700' }],
        'body-md': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'label-md': ['12px', { lineHeight: '16px', letterSpacing: '0.03em', fontWeight: '600' }],
        'label-lg': ['14px', { lineHeight: '18px', letterSpacing: '0.02em', fontWeight: '600' }],
        'headline-xl-mobile': ['26px', { lineHeight: '32px', letterSpacing: '-0.02em', fontWeight: '800' }],
        'label-sm': ['10px', { lineHeight: '14px', letterSpacing: '0.05em', fontWeight: '700' }],
        'price-headline': ['18px', { lineHeight: '22px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'body-sm': ['12px', { lineHeight: '16px', fontWeight: '400' }],
        'headline-lg-mobile': ['20px', { lineHeight: '26px', letterSpacing: '-0.015em', fontWeight: '700' }],
        'headline-lg': ['24px', { lineHeight: '30px', letterSpacing: '-0.015em', fontWeight: '700' }],
        'body-lg': ['16px', { lineHeight: '24px', fontWeight: '500' }],
        'headline-xl': ['32px', { lineHeight: '40px', letterSpacing: '-0.02em', fontWeight: '800' }],
      },
    },
  },
  plugins: [],
};
